name: Unity CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Setup Unity
        uses: game-ci/unity-builder@v2
        with:
          unityVersion: 2022.3.24f1
          targetPlatform: Android

      - name: Run Unit Tests
        id: test
        run: |
          ./Unity -runTests -testPlatform playmode -logFile test-results.log || true

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test Results
          path: test-results.log

      - name: Build APK
        run: ./Unity -buildTarget Android -executeMethod BuildScript.Build

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FastTV.apk
          path: Builds/FastTV.apk
